# Pandas
- 데이터 분석을 위한 파이썬 라이브러리. 대용량 데이터 처리에 강력
- Series(1차원), DataFrame(2차원) 구조 제공
- Series는 np.array와 유사하지만, 인덱스와 데이터가 함께 관리됨(딕셔너리와 닮음.)

### Pandas 주요 함수 및 메서드

**Series 생성 및 속성**
| 함수/메서드 | 설명 | 반환형 |
|------|------|------|
| `pd.Series(data, index=None, name=None)` | Series 생성 (data: 리스트, 딕셔너리, 스칼라 등), data가 스칼라면 인덱스의 모든 값을 data로 설정함. | Series |
| `series.values` | Series의 데이터 배열 반환 | numpy.ndarray |
| `series.index` | Series의 인덱스 반환 | Index |
| `series.dtype` | Series의 데이터 타입 | dtype |
| `series.name` | Series의 이름 (읽기/쓰기) | str or None |

**DataFrame 생성 및 기본 조작**
| 함수/메서드 | 설명 | 반환형 |
|------|------|------|
| `pd.DataFrame(data, index=None, columns=None)` | DataFrame 생성 | DataFrame |
| `df[column_name]` | 열 선택 (Series 반환) | Series |
| `df[[col1, col2]]` | 여러 열 선택 (DataFrame 반환) | DataFrame |
| `df.column_name` | 열 접근 (속성 방식) | Series |
| `df.index` | 행 인덱스 | Index |
| `df.columns` | 열 이름 | Index |
| `df.dtypes` | 각 열의 데이터 타입 | Series |
| `df.describe()` | 수치형 데이터의 통계 정보 | DataFrame |

**인덱싱 및 선택**
| 함수/메서드 | 설명 | 반환형 |
|------|------|------|
| `df.loc[label]` | 라벨(인덱스명)로 행/열 선택 (끝 포함) | Series or DataFrame |
| `df.loc[start:end, col]` | 라벨 슬라이싱 (끝 포함) | Series or DataFrame |
| `df.iloc[position]` | 정수 위치로 행/열 선택 (끝 미포함) | Series or DataFrame |
| `df.iloc[start:end, start:end]` | 정수 위치 슬라이싱 (끝 미포함) | DataFrame |
| `df[df[col] >= value]` | 불리언 마스킹으로 행 필터링 | DataFrame |

**행/열 추가 및 삭제**
| 함수/메서드 | 설명 | 반환형 |
|------|------|------|
| `df[new_col] = value` | 새 열 추가 (스칼라, 배열, Series 모두 가능) | None (제자리 수정) |
| `df.loc[new_label, :] = values` | 라벨로 새 행 추가 | None (제자리 수정) |
| `df.drop(label, axis=0, inplace=False)` | 행(axis=0) 또는 열(axis=1) 삭제 (copy 반환) | DataFrame or None |
| `del df[column]` | 열 즉시 삭제 | None |

**인덱스 및 재구성**
| 함수/메서드 | 설명 | 반환형 |
|------|------|------|
| `pd.date_range(start, periods=None, freq='D')` | 날짜 범위 생성 | DatetimeIndex |
| `pd.to_datetime(arg, format=None)` | 문자열/숫자를 datetime 객체로 변환 | Timestamp or Series or DatetimeIndex |
| `df.index = new_index` | 인덱스 변경 | None (제자리 수정) |
| `df.index.name = "name"` | 인덱스 이름 지정 | None (제자리 수정) |
| `df.columns.name = "name"` | 열 이름(컬럼명의 이름) 지정 | None (제자리 수정) |
| `df.reindex(index=..., columns=...)` | 인덱스와 열 순서 재구성 (새 DataFrame 반환) | DataFrame |
| `pd.permutation(x)` | 배열/범위를 무작위 순서로 섞음 | numpy.ndarray |

**정렬**
| 함수/메서드 | 설명 | 반환형 |
|------|------|------|
| `df.sort_index(axis=0, ascending=True)` | 인덱스로 정렬 (axis=0: 행, axis=1: 열) | DataFrame or None |
| `df.sort_values(by=col_name, ascending=True)` | 특정 열 값으로 정렬 | DataFrame or None |
| `df.sort_values(by=[col1, col2], ascending=[True, False])` | 다중 열 정렬 (우선순위, 각각 방향 지정 가능) | DataFrame or None |

**통계 및 집계**
| 함수/메서드 | 설명 | 반환형 |
|------|------|------|
| `df.count()` | 각 열의 비-NaN 데이터 개수 | Series |
| `df.sum(axis=None)` | 합계 (axis=None: 전체, axis=0: 열단위, axis=1: 행단위) | Series or scalar |
| `df.mean(axis=None)` | 평균 | Series or scalar |
| `df.median(axis=None)` | 중앙값 | Series or scalar |
| `df.std(axis=None)` | 표준편차 | Series or scalar |
| `df.var(axis=None)` | 분산 | Series or scalar |
| `df.min(), df.max()` | 최소, 최대값 | Series or scalar |
| `df.idxmin(), df.idxmax()` | 최소/최대값의 인덱스 반환 | Series |
| `df.quantile(q=0.5, axis=None)` | 사분위수 (q=0.25, 0.5, 0.75 등) | Series or DataFrame |
| `df.cumsum(axis=None)` | 누적합 | DataFrame or Series |
| `df.cumprod(axis=None)` | 누적곱 | DataFrame or Series |
| `df.abs()` | 절댓값 | DataFrame |
| `df.corr()` | 상관계수 행렬 | DataFrame |
| `series1.corr(series2)` | 두 Series 간 상관계수 | float |
| `series1.cov(series2)` | 두 Series 간 공분산 | float |

**Key Points**
- `loc[]`: 라벨 기반, 끝 포함 (inclusive)
- `iloc[]`: 정수 위치 기반, 끝 미포함 (exclusive)
- `drop()`: 새로운 복사본 반환 (view 아님), `inplace=True`로 원본 수정 가능
- DataFrame에 Series 추가: 인덱스 기반으로 정렬됨
- 불리언 조건 필터링: `df[column] operator value` 형태

In [81]:
import pandas as pd
import numpy as np

In [3]:
obj = pd.Series([4,7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj.dtypes

dtype('int64')

In [26]:
obj2 = pd.Series([1,2,3,4.0], index=['a','b','c','d'])
obj2

a    1.0
b    2.0
c    3.0
d    4.0
dtype: float64

In [27]:
obj2.dtypes

dtype('float64')

In [32]:
obj3 = pd.Series({'a': 1, 'b': 2})
obj3

a    1
b    2
dtype: int64

In [36]:
obj3.name = 'Series from dict'
obj3.index.name = 'key'

obj3

key
a    1
b    2
Name: Series from dict, dtype: int64

In [77]:
data = {
    'num': [1,2,3,4],
    'year': [2021, 2022, 2026, 2025],
    'point': [1.0, 2.0, 4.0, 5.0]
}
# 인덱스는 크기가 반드시 일치해야 한다.
df1 = pd.DataFrame(data, index=pd.RangeIndex(2, 6))
df2 = pd.DataFrame(data, columns=['year', 'point', 'num', 'unknown'], index=[1,2,3,4]) # column 은 dict의 각 키를 찾는다. 없으면 NaN으로 채워지고 추후 계산불가.
df1, df2, df2.describe()
# describe는 계산 가능한 값들에 대한 다양한 계산 값을 출력

(   num  year  point
 2    1  2021    1.0
 3    2  2022    2.0
 4    3  2026    4.0
 5    4  2025    5.0,
    year  point  num unknown
 1  2021    1.0    1     NaN
 2  2022    2.0    2     NaN
 3  2026    4.0    3     NaN
 4  2025    5.0    4     NaN,
               year     point       num
 count     4.000000  4.000000  4.000000
 mean   2023.500000  3.000000  2.500000
 std       2.380476  1.825742  1.290994
 min    2021.000000  1.000000  1.000000
 25%    2021.750000  1.750000  1.750000
 50%    2023.500000  3.000000  2.500000
 75%    2025.250000  4.250000  3.250000
 max    2026.000000  5.000000  4.000000)

In [70]:
df1.num, df1['num']

(2    1
 3    2
 4    3
 5    4
 Name: num, dtype: int64,
 2    1
 3    2
 4    3
 5    4
 Name: num, dtype: int64)

In [71]:
df1[['year', 'point']]

   year  point
2  2021    1.0
3  2022    2.0
4  2026    4.0
5  2025    5.0

In [78]:
df2.unknown = 0.5
df2

   year  point  num  unknown
1  2021    1.0    1      0.5
2  2022    2.0    2      0.5
3  2026    4.0    3      0.5
4  2025    5.0    4      0.5

In [79]:
df2['unknown'] = [1.0, 2.0, 3.0, 4.0]
df2

   year  point  num  unknown
1  2021    1.0    1      1.0
2  2022    2.0    2      2.0
3  2026    4.0    3      3.0
4  2025    5.0    4      4.0

In [88]:
df3 = pd.DataFrame({
    'num': [1,2,3,4],
    'year': [2021, 2022, 2026, 2025],
    'point': [1.0, 2.0, 4.0, 5.0]
})

df3

   num  year  point
0    1  2021    1.0
1    2  2022    2.0
2    3  2026    4.0
3    4  2025    5.0

In [87]:
df3['test'] = np.arange(4)
# df3.test2 = np.arange(4) 불가능!
df3

   num  year  point  test
0    1  2021    1.0     0
1    2  2022    2.0     1
2    3  2026    4.0     2
3    4  2025    5.0     3

In [94]:
df4 = pd.DataFrame({
    'num': [1,2,3,4],
    'year': [2021, 2022, 2026, 2025],
    'point': [1.0, 2.0, 4.0, 5.0]
}, index=['a','b','c','d'])

val = pd.Series([1,2,3, 4, 5], index=['d', 'c', 'b', 'a', 'e']) # python list와 numpy array와 다른점!
df4['plus'] = val # index에 맞게 채워짐. DataFrame에 있는 index가 Series에 없으면 오류.
df4

   num  year  point  plus
a    1  2021    1.0     4
b    2  2022    2.0     3
c    3  2026    4.0     2
d    4  2025    5.0     1

In [95]:
df5 = pd.DataFrame({
    'num': [1,2,3,4],
    'year': [2021, 2022, 2026, 2025],
    'point': [1.0, 2.0, 4.0, 5.0]
}, index=['a','b','c','d'])

df5['mask'] = df5['year'] >= 2025
df5

   num  year  point   mask
a    1  2021    1.0  False
b    2  2022    2.0  False
c    3  2026    4.0   True
d    4  2025    5.0   True

In [96]:
df6 = pd.DataFrame({
    'num': [1,2,3,4],
    'year': [2021, 2022, 2026, 2025],
    'point': [1.0, 2.0, 4.0, 5.0]
}, index=['a','b','c','d'])

del df6['point']
df6

   num  year
a    1  2021
b    2  2022
c    3  2026
d    4  2025

In [97]:
df7 = pd.DataFrame({
    'num': [1,2,3,4],
    'year': [2021, 2022, 2026, 2025],
    'point': [1.0, 2.0, 4.0, 5.0]
}, index=['a','b','c','d'])

df7.index.name = "IDX"
df7.columns.name ="COL"
df7

COL  num  year  point
IDX
a      1  2021    1.0
b      2  2022    2.0
c      3  2026    4.0
d      4  2025    5.0

In [101]:
df7[0:3]

COL  num  year  point
IDX
a      1  2021    1.0
b      2  2022    2.0
c      3  2026    4.0

In [102]:
df7.loc['a']

COL
num         1.0
year     2021.0
point       1.0
Name: a, dtype: float64

In [ ]:
df7.loc['a':'c'] # *** 이건 end를 포함함! ***

COL  num  year  point
IDX
a      1  2021    1.0
b      2  2022    2.0
c      3  2026    4.0

In [105]:
df7.loc['a':'c', 'point']

IDX
a    1.0
b    2.0
c    4.0
Name: point, dtype: float64

In [107]:
df7.loc[:, 'year':'point']

COL  year  point
IDX
a    2021    1.0
b    2022    2.0
c    2026    4.0
d    2025    5.0

In [120]:
df8 = pd.DataFrame({
    'num': [1,2,3,4],
    'year': [2021, 2022, 2026, 2025],
    'point': [1.0, 2.0, 4.0, 5.0]
}, index=['a','b','c','d'])

df8.loc['az', :] = [7, 2222, 10.0] # 이렇게도 추가 가능
df8.loc[:, 'num'] = [7,6,5,4,3] # 이렇게도 추가 가능

df8

    num    year  point
a   7.0  2021.0    1.0
b   6.0  2022.0    2.0
c   5.0  2026.0    4.0
d   4.0  2025.0    5.0
az  3.0  2222.0   10.0

In [ ]:
df9 = pd.DataFrame({
    'num': [1,2,3,4],
    'year': [2021, 2022, 2026, 2025],
    'point': [1.0, 2.0, 4.0, 5.0]
}, index=['a','b','c','d'])

df9.iloc[1:3, 1:3] # 이건 end 포함 x
df9.iloc[1:3, 1:3] = [[1,2.0], [3, 3.0]] # 이렇게 수정 가능
df9

   num  year  point
a    1  2021    1.0
b    2     1    2.0
c    3     3    3.0
d    4  2025    5.0

In [136]:
df10 = pd.DataFrame({
    'num': [1,2,3,4],
    'year': [2021, 2022, 2026, 2025],
    'point': [1.0, 2.0, 4.0, 5.0]
}, index=['a','b','c','d'])

df10[df10['num'] >= 3]

   num  year  point
c    3  2026    4.0
d    4  2025    5.0

In [ ]:
df10.index = pd.date_range('20260325', periods=4, freq='s') # 가본은 D(date)
# to_datatime('20260325') 으로 datetime 객체 받을 수 있음. 
df10.index

DatetimeIndex(['2026-07-01 00:00:00', '2026-07-01 00:00:01',
               '2026-07-01 00:00:02', '2026-07-01 00:00:03'],
              dtype='datetime64[ns]', freq='s')

In [ ]:
df11 = pd.DataFrame({
    'num': [1,2,3,4],
    'year': [2021, 2022, 2026, 2025],
    'point': [1.0, 2.0, 4.0, 5.0]
}, index=['a','b','c','d'])

df11.drop('a') # a 행을 지운 새로운 DataFrame 반환. view가 아닌 copy임.

   num  year  point
b    2  2022    2.0
c    3  2026    4.0
d    4  2025    5.0

In [ ]:
df11.drop('num', axis=1) # num 열을 지운 새로운 DataFrame 반환

   year  point
a  2021    1.0
b  2022    2.0
c  2026    4.0
d  2025    5.0

In [ ]:
df12 = pd.DataFrame({
    'num': [1,2,3,4],
    'year': [2021, 2022, 2026, 2025],
    'point': [1.0, 2.0, 4.0, 5.0]
}, index=['a','b','c','d'])

df12.count(), df12.min(), df12.max(axis=None), df12.idxmax(), df12.idxmin(), df12.quantile(), df12.sum(), df12.mean(), df12.median(), df12.abs(), df12.std(), df12.var(), df12.cumsum(), df12.cumprod()

# argmin, argmax, mad는 없는데???

(num      4
 year     4
 point    4
 dtype: int64,
 num         1.0
 year     2021.0
 point       1.0
 dtype: float64,
 2026.0,
 num      d
 year     c
 point    d
 dtype: object,
 num      a
 year     a
 point    a
 dtype: object,
 num         2.5
 year     2023.5
 point       3.0
 Name: 0.5, dtype: float64,
 num        10.0
 year     8094.0
 point      12.0
 dtype: float64,
 num         2.5
 year     2023.5
 point       3.0
 dtype: float64,
 num         2.5
 year     2023.5
 point       3.0
 dtype: float64,
    num  year  point
 a    1  2021    1.0
 b    2  2022    2.0
 c    3  2026    4.0
 d    4  2025    5.0,
 num      1.290994
 year     2.380476
 point    1.825742
 dtype: float64,
 num      1.666667
 year     5.666667
 point    3.333333
 dtype: float64,
    num  year  point
 a    1  2021    1.0
 b    3  4043    3.0
 c    6  6069    7.0
 d   10  8094   12.0,
    num            year  point
 a    1            2021    1.0
 b    2         4086462    2.0
 c    6      8279172012    8.0
 d   24  16765323324300   40.0)

In [ ]:
df13 = pd.DataFrame(np.random.randn(6,4), columns=['a','b','c','d'], index=pd.date_range("20260325", periods=6))
df13['a'].corr(df13['b']), df13['a'].cov(df13['b'])
# 상관 계수                     공분산
# 공분산을 표준화(nomalize) 시 상관 계수가 됨.

(0.29905775569917287, 0.3064498736985068)

In [234]:
df14 = pd.DataFrame({
    'num': [1,2,3,4],
    'year': [2021, 2022, 2026, 2025],
    'point': [1.0, 3.0, 2.0, 5.0]
}, index=pd.date_range('20260325', periods=4))

suf = np.random.permutation(df14.index)
df15 = df14.reindex(index=suf, columns=np.random.permutation(df14.columns)) # 새롭게 인덱스와 열을 바꾼 DF 반환
df15

            year  num  point
2026-03-25  2021    1    1.0
2026-03-28  2025    4    5.0
2026-03-27  2026    3    2.0
2026-03-26  2022    2    3.0

In [235]:
df15.sort_index(axis=0)

            year  num  point
2026-03-25  2021    1    1.0
2026-03-26  2022    2    3.0
2026-03-27  2026    3    2.0
2026-03-28  2025    4    5.0

In [236]:
df15.sort_index(axis=1)

            num  point  year
2026-03-25    1    1.0  2021
2026-03-28    4    5.0  2025
2026-03-27    3    2.0  2026
2026-03-26    2    3.0  2022

In [237]:
df15.sort_index(ascending=False)

            year  num  point
2026-03-28  2025    4    5.0
2026-03-27  2026    3    2.0
2026-03-26  2022    2    3.0
2026-03-25  2021    1    1.0

In [242]:
df15.sort_values(by='point')

            year  num  point
2026-03-25  2021    1    1.0
2026-03-27  2026    3    2.0
2026-03-26  2022    2    3.0
2026-03-28  2025    4    5.0

In [ ]:
df15.sort_values(by=['num','point']) # 정렬 우선순위. num 값이 같으면 point로 정렬

            year  num  point
2026-03-25  2021    1    1.0
2026-03-26  2022    2    3.0
2026-03-27  2026    3    2.0
2026-03-28  2025    4    5.0

In [ ]:
df15.sort_values(by=['num','point'], ascending=[True, False]) # 정렬 우선순위. num 값이 같으면 point 내림차순 로 정렬